service: function-with-environment-variables

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  createUser:
    handler: dist/sample/handler.createUser
    events:
      - http:
          path: /test/original
          method: POST
    package:
      patterns:
        # - "!./**"
        - 'dist/sample/index.js'
        - 'package.json'
        - 'package-lock.json'
        - 'node_modules/**/*'